pipeline {
    agent any 
    
    stages { 
        stage('SCM Checkout') {
            steps {
                retry(3) {
                    git branch: 'main', url: 'https://github.com/neroIJN/Movie-app-React'
                }
            }
        }
        stage('Build Docker Image') {
            steps {  
                bat 'docker build -t adomicarts/my-node-app:%BUILD_NUMBER% .'
            }
        }
        stage('Login to Docker Hub') {
            steps {
                withCredentials([string(credentialsId: 'Docker_hub', variable: 'test-docker')])  {
                    script {
                        bat "docker login -u itznero -p %{test-docker%}"
                    }
                }
            }
        }
        stage('Push Image') {
            steps {
                bat 'docker push itznero/my-node-app:%BUILD_NUMBER%'
            }
        }
    }
    post {
        always {
            bat 'docker logout'
        }
    }
}